### ISSUE TITLE
Reinforcement Learning - Where Art Thou?

### ISSUE THREAD

**Issue by Hackathorn** [rasbt/python-machine-learning-book#23]
Wonderful book; learning a ton! Question: In first chapter, you explain the three types of learning (supervised, unsupervised and reinforcement). Usually the third is not listed. So, I search your text for other material on RL but found none. Future chapter in next edition? Future book? In your other resources, are there links about RL with a scikit-learn style? Love [Karpathy's blog](https://karpathy.github.io/2016/05/31/rl/) on "Pong from Pixels".

**Comment by rasbt** [comment]
Thanks for the nice words, Richard, I really appreciate it, and I am happy to hear that you like it overall -- despite the "missing" reinforcement learning chapter(s) :). 

> Usually the third is not listed. So, I search your text for other material on RL but found none. Future chapter in next edition? Future book?

Yeah, I had a hard time to meet the max. page limits by the publisher, and I thought that a reinforcement learning chapter was a bit out of scope. Sure, an intro chapter would be a great idea for a second edition (alternatively, I was thinking on separate chapters on recurrent neural nets and ConvNets). To be honest though, I'd say that Reinforcement Learning would really be a better off as a separate, future book :). I thought it would be a good idea mentioning it in the intro though for the sake of completeness (i.e., letting readers know that it exists :P).

PS: I just wanted to mention Andrej Karpathy's blog, but I see that you already stumbled upon it. Coincidentally, there's an online course on reinforcement learning that just started 2 days ago, maybe that's a useful resource: https://onlinecourses.nptel.ac.in/noc16_cs09/preview
(It's based on *R. S. Sutton and A. G. Barto. Reinforcement Learning - An Introduction. MIT Press. 1998.*)

Cheers,
Sebastian
