### ISSUE TITLE
Cannot run a line of code

### ISSUE THREAD

**Issue by Surry47** [rasbt/python-machine-learning-book#28]
When I run this script in python notebook:

https://github.com/rasbt/python-machine-learning-book/blob/master/code/optional-py-scripts/ch02.py

The last line (ada.partial_fit(X_std[0, :], y[0])) gives the error:

<__main__.AdalineSGD at 0x10a89fac8>

**Comment by rasbt** [comment]
Thanks for the note. The line `<main.AdalineSGD at 0x10a89fac8>` is not an error as far as I can tell: The `fit` and `partial_fit` methods return the AdalineSGD object (`self`) itself.  I just updated the code to `ada = ada.partial_fit(X_std[0, :], y[0])` to avoid confusion. Let me know if you have any other questions. (PS: In general, I would recommend using the Jupyter notebooks if you have jupyter notebook installed on your machine).

Cheers,
Sebastian
