### ISSUE TITLE
Errata update question

### ISSUE THREAD

**Issue by traits** [rasbt/python-machine-learning-book#3]
Regarding your remark:

> [2015-10-20] Good news! I just heard back from the publisher; all the typos and errors which are listed below will be fixed by next week.

I bought the ebook yesterday (O'Reilly, not PACKT) and found some errors. Up to now, they are in the errata (v2), but not yet fixed in my fresh copy.  Can you say something about the current state, are the updates for immediate PACKT customers only?

edit: 
Interestingly, my copy stands the test on page viii (so I have _Classifiers_ there), but for example not the one regarding the inverted _'y'_ variants (with and w/o caret) on page 22 and also the following errors (p. 23) are still present.

**Comment by rasbt** [comment]
Thanks for the feedback @traits . I am afraid to say so, but the errata v2 reflects the most up to date version of the book -- unfortunately, all the errors listed there are still present. Sorry, I know this is very frustrating, and I personally wish that these get fixed as well! I've emailed the publisher a few weeks back but haven't received any response, yet. However, I will just email them again today and let you know about their plans regarding another update (as soon as they respond). 

Cheers,
Sebastian

**Comment by rasbt** [comment]
I have some great news regarding the update :)! 

> we tend to only do it once ... However, in your case I can have the book re-uploaded for a final time. [...] Once you're happy, and if you think we have ironed out all the issues, please send over a folder with all the changes. I will pass that on to production and have the book re-uploaded as quickly as possible.

**Comment by traits** [comment]
That sounds like good news!

Michael

**Comment by rasbt** [comment]
Just a quick update on this issue: I just received another response from the publisher that the layout team already started working on the update. It may take a while (~ 2 weeks) until it is uploaded though (it's normal procedure), but I will keep you posted once it's done!

**Comment by rasbt** [comment]
Yet another quick update: I just received the draft document from layout team the other day ... There are still a couple of issues that need to be addressed. Depending on how long it takes to apply the fixes, the "new" update may be uploaded next week or the week after. Sorry for the trouble, and I will keep you updated!

**Comment by rasbt** [comment]
Just got the tentative republishing date from the layout team: It's April 19th, 2016. I just went over the revised layout this weekend, and it looks like all the issues listed in the errata have been addressed :).

**Comment by rasbt** [comment]
I checked my Packt account a few days ago and the good news is that the revision has been uploaded successfully. It seems though that the revised version is not available via O'Reilly, yet. Let me close this issue and continue the O'Reilly-related discussion on the related issue here #7
