### ISSUE TITLE
Missing code in chapter 11

### ISSUE THREAD

**Issue by maxcuz** [rasbt/python-machine-learning-book#38]
Hi, below code is from the book but missing in the cell **In[17]** of ch11.ipynb.

`row_clusters = linkage(df.values, method='complete', metric='euclidean')`

![capture](https://cloud.githubusercontent.com/assets/1693094/21614938/7eadd078-d216-11e6-9b2c-3963b13cf4e4.PNG)

**Comment by rasbt** [comment]
Thanks for the note, haven't noticed that! Yeah, without that line, the output may be quite misleading since it was supposed to show that the two approaches are equivalent. Just added it! Thanks
