### ISSUE TITLE
Adding the iris.data file back into the repo

### ISSUE THREAD

**Issue by jay-johnson** [rasbt/python-machine-learning-book#44]
Can the iris.data file be added back into the repo on master?

Here's the last version I believe:
https://github.com/rasbt/python-machine-learning-book/blob/194e34f245abb97f53d0e72166ab6785d01a1e94/code/datasets/iris/iris.data

Thanks again!

**Comment by rasbt** [comment]
Thanks for the note. I am not sure why it was removed at some point ... it must have happened by accident! It should be back now
