### ISSUE TITLE
Issues when installing Keras on Windows 10 64bit machines

### ISSUE THREAD

**Issue by melzoghbi** [rasbt/python-machine-learning-book#47]
Hi,

I had an issue when installing Keras on Windows 10 64bit machine (as described in ch13) but this did not work. I have posted the solution in a step by step here in this blog post:

[install keras on windows 10 x64 bit machine ](http://www.mostafaelzoghbi.com/2017/04/how-to-install-keras-on-windows-10-64.html
)
@rasbt : feel free to add it to the notes of the labs in GitHub.

Thanks.

**Comment by rasbt** [comment]
thanks for the instructions/note, I will add a comment to the notebook
