### ISSUE TITLE
Typo/Clarification on Ch02.ipynb

### ISSUE THREAD

**Issue by mastash3ff** [rasbt/python-machine-learning-book#52]
There is an _Additional Note (1)_ section where it says: " If all the weights are initialized to 0, only the scale of the weight vector, not the direction."

Seems there is some missing meaning in that sentence.  Was wondering if you could correct it please.  Thank you very much!

**Comment by rasbt** [comment]
Thanks for the note. It should say "If all the weights are initialized to 0, the learning rate parameter eta affects only the scale of the weight vector but not its direction." Just fixed it.
