### ISSUE TITLE
question about in [29]

### ISSUE THREAD

**Issue by shaoeChen** [rasbt/python-machine-learning-book#57]
dear sir..
i try to study Machine Learning through your book 『Python Machine Learning』, and it's very nick book!
i can't understand how you to set up 『param_grid』
i try to get the information from sklearn but it just say『dict or list of dictionaries』
even the sample , it just write 『param_grid=....』
So ... about the 『param_grid』 how do i set it up!
i am sorry my english is a little week!
i hope i can let you know my question and thank you very much!

**Comment by rasbt** [comment]
Hi there,
Note sure how far you've read in the book, but there are a few examples in chapter 6, in the section *Fine-tuning machine learning models via grid search*. (And here are the corresponding code examples: https://github.com/rasbt/python-machine-learning-book/blob/master/code/ch06/ch06.ipynb).

Does that help?
