### ISSUE TITLE
Couldn't get desired output from Adaptive linear neuron implementation 

### ISSUE THREAD

**Issue by sohaibfarooqi** [rasbt/python-machine-learning-book#68]
Hi,
I was trying out one of the example in `Chapter2`, under title: **Implementing an adaptive linear neuron in Python** ([Link to notebook](https://github.com/rasbt/python-machine-learning-book/blob/master/code/ch02/ch02.ipynb)). 
The problem is when I plot decision boundaries, whole area is shown red.
<img width="639" alt="screen shot 2017-12-02 at 22 21 25" src="https://user-images.githubusercontent.com/13061583/33516532-3714e45a-d7af-11e7-8559-33cb9a86f3dd.png">

When I change `output = self.activation(X)` to `output = self.predict(X)`inside `fit` function, the problem seems to be gone.
<img width="637" alt="screen shot 2017-12-02 at 22 21 00" src="https://user-images.githubusercontent.com/13061583/33516535-49e7e7bc-d7af-11e7-954d-13899e2287ce.png">

Is there an issue with the code or the code is correct and I made some other mistake while implementing? 

Thanks
Sohaib

**Comment by AnshuAyush** [comment]
I guess Your code is correct with proper decision boundary b/w iris flowers with proper explanation.
