### ISSUE TITLE
Updated ebook not yet available from O'Reilly

### ISSUE THREAD

**Issue by gbuesing** [rasbt/python-machine-learning-book#7]
Just a heads up on this -- I checked my O'Reilly account, and they did not yet have the updated version.

I'll post here once it appears.

**Comment by rasbt** [comment]
Sorry for the inconvenience, Geoff. I emailed the publisher on Sunday asking about a tentative date for the re-upload on O'Reilly's servers. Unfortunately, I haven't heard back from them, yet, but I will let you know once I know more!

**Comment by miguelsaddress** [comment]
I dont know how I can compare the editions right now, but I would say the new one is uploaded as they said in their email. Now I have this one, from 2016. 

![pyml](https://cloud.githubusercontent.com/assets/1411774/14868286/218b8480-0ccd-11e6-8b90-fe9e145f0bef.png)

**Comment by rasbt** [comment]
Oh, nice, thanks for the note, Miguel! Looks it's gone live on O'Reilly then :). Maybe one way to confirm would be to look at the reinforcement learning figure on page 6

![errata_2016-04-22](https://cloud.githubusercontent.com/assets/5618407/14868779/6a3285b0-0c9d-11e6-8ce5-314322a65d59.jpg)

**Comment by gbuesing** [comment]
@miguelsaddress what email are you referring to?

The O'Reilly book page shows a publication date as "September 2015": http://shop.oreilly.com/product/9781783555130.do?sortby=publicationDate

And if I log into Your Products > Ebooks, I see the September 2015 version as well.

**Comment by miguelsaddress** [comment]
in my case both look the same...

This is the old one (purchased december 2015)
![old](https://cloud.githubusercontent.com/assets/1411774/14870163/bc2bd408-0cd8-11e6-9745-069352b29d4b.png)

and this is the "maybe-new-one" downloaded today...
![maybe-new](https://cloud.githubusercontent.com/assets/1411774/14870169/cddd1478-0cd8-11e6-95d6-c88c57a73e20.png)

@gbuesing I got an email last weekend to confirm my address to receive a new paper copy of the book
![mail](https://cloud.githubusercontent.com/assets/1411774/14870201/05195ef6-0cd9-11e6-857c-1e7df64e3d86.png)

**Comment by gbuesing** [comment]
@miguelsaddress thanks for sharing -- looks like you got the communication from Packt, not O'Reilly.

So, still waiting on O'Reilly to update.

**Comment by rasbt** [comment]
@miguelsaddress Oh, I see, so the screenshot above is from the updated ebook that you downloaded from Packt, not O'Reilly? In any case, I am really happy that they send you a new copy without much hassle :)

**Comment by miguelsaddress** [comment]
oops, my bad

yes it is from packt, sorry ^__^U

**Comment by traits** [comment]
I can confirm, that there is nothing new from O'Reilly. This is from the example above (and matches my accounts  "Updated" entry (Nov 19, 2015))

**Comment by rasbt** [comment]
Thanks for all the info. Unfortunately, I still haven't got a response regarding the re-upload on O'Reilly. Since it sounds like the book has already been updated once (Nov 19, 2015), I think there shouldn't be a technical hurdle for doing this a second time. I hope it's just a matter of time. I will keep you updated once I know more!

**Comment by gbuesing** [comment]
Looks like it's been updated!

I just checked my O'Reilly account this morning -- ebook now shows Updated April 28, 2016. Downloaded and it was indeed the latest version with the correct reinforcement learning figure on page 6.

Product page still shows September 2015, but I assume that new purchasers would get the updated book.

**Comment by rasbt** [comment]
Thanks for the update, happy to hear that the revision is available via O'Reilly as well, now! :)
