### ISSUE TITLE
Chapter 15: Padding modes figure

### ISSUE THREAD

**Issue by tynowell** [rasbt/python-machine-learning-book#78]
On page 500 (second edition: September 2017) there is a figure illustrating Full, Same and Valid padding and how the pixel patches map to the feature maps. 

The feature map of the valid padding example is only 2x2. It specifies a 5x5 pixel input, 3x3 filter and a stride of 1. The feature map should be of size 3x3.

**Comment by rasbt** [comment]
Thanks for the comment. We had addressed this in a reprint about a year ago (~around July 2018). It seems you have an older version before this wasn't fixed. For reference, the updated figure can be found here: https://raw.githubusercontent.com/rasbt/python-machine-learning-book-2nd-edition/master/code/ch15/images/15_11.png
