### ISSUE TITLE
Incorrect results printed for MLPGradientCheck

### ISSUE THREAD

**Issue by zhangzfmail** [rasbt/python-machine-learning-book#9]
I was running MLPGradientCheck, but the results are different from example
When I tried to locate the problem, I found that a3 in MLPGradientCheck.fit is always "nan"
Is that normal? how could I fix it

![problem](https://cloud.githubusercontent.com/assets/15005793/15622696/56ae54fc-2439-11e6-9c94-d8a5e55cdf17.png)

**Comment by rasbt** [comment]
Thanks for the additional info, less discuss this further in the other issue you opened (#8) since this is likely a related problem :)
