### ISSUE TITLE
How to Use the code files

### ISSUE THREAD

**Issue by Gomzzz93** [rasbt/python-machine-learning-book#92]
Hi, I am extremely new to Python and I understand how to write basic commands and stuff.
I got the Code files for the book but I am not able to understand how to use them for learning.
All of them seem to be in Text format.
How can I use them as code to make a new file in which I can just have the Code instead of all the text.
I just wanted to see how the code runs but I am unable to understand what this code is and how to extract things which I want instead of having to remove all the "" and /n and other formatting elements.
Thanks.
![text_code](https://user-images.githubusercontent.com/80556946/111015003-9689f280-8374-11eb-9ae0-c3b845df09b3.PNG)

**Comment by rasbt** [comment]
Hi there, I see you already closed the question, so I assume you solved it? Otherwise, let me know and I can explain.

**Comment by Gomzzz93** [comment]
I solved it. Thanks for everything.
